### PR TITLE
finish doc comments

### PR DESCRIPTION
**Pull request by nyx-litenite**
Adds basic documentation comments (in English) and fixes a deprecated syntax warning (line 71)

Btw great work on this! I love the simplicity of dotenv and it's great to have it ported to V!

### CODE REVIEW

**Review by zztkm — APPROVED** [review]
Thank you for your contribution!!!
I'm glad you left Japanese :D

This PR is LGTM!

**Comment by nyx-litenite** [comment]
You can merge this whenever you'd like then. Let me know if I can be of any aid with that.

**Comment by nyx-litenite** [comment]
Should be good to go. Both PR's are merged here, so it should be a clean merge for you. 

Should support:
```
TEST=OVERLOADENV
TEST2=LOADENV
#TEST3=NOLOADENV
TEST4=NOHASH#COMMENTSTARTSHERe
TEST5=NOHASH #TEST6=NOLOADENV
TEST7 = "HASH #ENV" # COMMENT
```

**Review by zztkm — APPROVED** [review]
lgtm!

**Review by zztkm — APPROVED** [review]
test approved!

**Comment by zztkm** [comment]
@nyx-litenite 
Thanks!

I have confirmed that all tests are OK.

i approved & merged!

**Comment by nyx-litenite** [comment]
Awesome! Glad to help :) I'll keep an eye on the roadmap issue for anything else i can help w/

**Comment by zztkm** [comment]
OK!

I would like to discuss the roadmap here(#11 ).
It will help you to implement what features in the future!

**Pull request merged**
